# Generated by Django 3.2.12 on 2022-03-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ptt_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.TextField()),
                ('BOARD', models.TextField()),
                ('URL', models.URLField()),
                ('AUTHOR', models.TextField()),
                ('NRECS', models.IntegerField()),
                ('C_TIME', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
