# Generated by Django 3.2.12 on 2022-03-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pttApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ptt_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.TextField()),
                ('URL', models.URLField()),
                ('NRECS', models.IntegerField()),
                ('C_TIME', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
